### ISSUE TITLE
[BUG] whereJoin is using wrong column for SQL joining 

### ISSUE THREAD

**Issue by delmicio** [fico7489/laravel-eloquent-join#8]
Hi, I've tried a simple query for testing a realation using whereJoin
`App\Models\ZoomMeeting::whereJoin('live_class.id', '>', 0)->count()`

But it fails showing this:
```
Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 
Unknown column 'live_classes.live_class_id' in 'on clause' (SQL: select count(*) as aggregate from 
`zoom_meetings` left join `live_classes` on `live_classes`.`live_class_id` = `zoom_meetings`.`live_class_id` 
where `live_classes`.`id` > 0 group by `zoom_meetings`.`live_class_id`)'
```

The problem is that is using **live_classes.live_class_id** for joining when it should be using **live_classes.id**

```PHP
class ZoomMeeting extends Eloquent
{
    protected $primaryKey = 'live_class_id';
    public $incrementing = false;

    protected $casts = [
        'live_class_id' => 'int'
    ];

    public function live_class()
    {
        return $this->belongsTo(\App\Models\LiveClass::class);
    }
}

class LiveClass extends Eloquent
{
    public function zoom_meeting()
    {
        return $this->hasOne(\App\Models\ZoomMeeting::class);
    }
}
```

**Comment by fico7489** [comment]
I think that your ZoomMeeting  model is not correct. 
protected $primaryKey should be 'id', 'zoom_meeting_id' or something like that, not 'live_class_id'.

live_class_id is forreign key not primary key,

**Comment by delmicio** [comment]
We are using 'live_class_id' on ZoomMeeting as primary key and as foreign key too, this is an allowed behaviour on laravel.

**Comment by fico7489** [comment]
yes of course it is allowed, but strange. I can check what is the problem if you send me your migrations or db schema for live_classes and live_classes tables...

**Comment by delmicio** [comment]
sure ...
```SQL
CREATE TABLE `zoom_meetings` (
  `live_class_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`live_class_id`),
  CONSTRAINT `FK_zoom_meeting_id__live_class_id` FOREIGN KEY (`live_class_id`) REFERENCES `live_classes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

CREATE TABLE `live_classes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),  
  KEY `live_classes_created_at_index` (`created_at`),
  KEY `live_classes_updated_at_index` (`updated_at`)
) ENGINE=InnoDB AUTO_INCREMENT=116028 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
Thank you for helping :heart:

**Comment by fico7489** [comment]
you are using live_class_id as primary and foreign key in zoom_meetings table and this can not be correct. You probably need this schema:

```
CREATE TABLE `zoom_meetings` (
      `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
      `live_class_id` int(10) unsigned NOT NULL,
     `created_at` timestamp NULL DEFAULT NULL,
     `updated_at` timestamp NULL DEFAULT NULL,
);
```

```
CREATE TABLE `live_classes` (
      `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
      `created_at` timestamp NULL DEFAULT NULL,
      `updated_at` timestamp NULL DEFAULT NULL,
);
```

id is primary key for zoom_meetings
id is primary key for live_classes
live_class_id is foreign key for zoom_meetings <-> live_classes relation

**Comment by delmicio** [comment]
But I don't need an AUTO_INCREMENT id column. Again, the schema is fine.
https://stackoverflow.com/questions/17636106/can-a-foreign-key-act-as-a-primary-key
```CMD
>>>  App\Models\LiveClass::first()->getKeyName()
=> "id"
>>>  App\Models\ZoomMeeting::first()->getKeyName()
=> "live_class_id"
```

Maybe you can use on your package a `getRelationships` method as here:
https://laracasts.com/discuss/channels/eloquent/get-all-model-relationships

**Comment by fico7489** [comment]
I never saw that someone is using the same field as primary and foreign key, but I guess it is possible. This is a some kind of an edge case, but yes, it's maybe a bug, I'll check in tomorrow and fix it if it's a bug.

**Comment by fico7489** [comment]
bugfix is pushed to all branches, can you try now ?

**Comment by delmicio** [comment]
I've updated and re-tried but got the same error.

```CMD
root@abb3d5449ddc:/var/www# artisan tinker
Psy Shell v0.8.17 (PHP 7.1.12-3+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> App\Models\ZoomMeeting::whereJoin('live_class.id', '>', 0)->count()
Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'live_classes.live_class_id' in 'on clause' (SQL: select count(*) as aggregate from `zoom_meetings` left join `live_classes` on `live_classes`.`live_class_id` = `zoom_meetings`.`live_class_id` where `live_classes`.`id` > 0 group by `zoom_meetings`.`live_class_id`)'
>>>
root@abb3d5449ddc:/var/www# composer show -- fico7489/laravel-eloquent-join
name     : fico7489/laravel-eloquent-join
descrip. : This package introduces the join capability for sorting and filtering on eloquent relations.
keywords : laravel, laravel eloquent join, laravel join relation, laravel join relations, laravel sort join, laravel where join
versions : * 2.1.3
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/fico7489/laravel-eloquent-join.git adc6c57016057b90dad1ed326bd68a3fc5c352f4
dist     : [zip] https://api.github.com/repos/fico7489/laravel-eloquent-join/zipball/adc6c57016057b90dad1ed326bd68a3fc5c352f4 adc6c57016057b90dad1ed326bd68a3fc5c352f4
names    : fico7489/laravel-eloquent-join

autoload
psr-4
Fico7489\Laravel\EloquentJoin\ => src

requires
illuminate/database 5.5.*

requires (dev)
orchestra/testbench ~3.5.0
```

**Comment by fico7489** [comment]
Thanks for bug report. I fixed and tested with your database and models and now everything seems fine now. Most of the people use 'id' for primary key and that is the reason why nobody reported this bug...

**Comment by delmicio** [comment]
Hey @fico7489 this issue is still present, you should not close it.
Were you able to reproduce it?

**Comment by fico7489** [comment]
It is fixed in 2.2.4 version I tested with your database...
